name: stocks
channels:
  - defaults
  - conda-forge
dependencies:
  - black
  - bs4
  - flake8
  - isort
  - jupyter
  - matplotlib
  - mypy
  - notebook
  - numpy
  - pandas
  - pandas-datareader
  - plotly
  - pytest
  - pytest-cov
  - python=3.11.8
  - python-dotenv
  - requests
  - yfinance
